---
- name: Configure the internal, physical server
  hosts: moonstack

  vars:
    sample_var: "a string"

  # tasks:
  #   - name: Install relevant packages
  #     become: true
  #     ansible.builtin.apt:
  #       # name: "{{ item }}"
  #       name: [virt-manager, acl, podman, podman-compose]
  #       state: present
  #     # Acl is needed for unprivileged user escalation:
  #     # https://docs.ansible.com/ansible-core/2.16/playbook_guide/playbooks_privilege_escalation.html#risks-of-becoming-an-unprivileged-user
  #     # loop: [virt-manager, acl, podman, podman-compose]

  roles:
    - role: rathole
      vars:
        rathole_role: "client"
        rathole_user: podmaner
        rathole_server_ip: "154.12.245.181"
        rathole_services:
          - name: http
            local_addr: "127.0.0.1:8080"
          - name: https
            local_addr: "127.0.0.1:8443"
    - role: caddy
      vars:
        caddy_services:
          - domain_name: "test.moonpiedumpl.ing"
            port: 8000 # This is where the python http server runs by default, for my tests.
          - domain_name: "sso.moonpiedumpl.ing"
            port: 9000
        caddy_trusted_proxies: ['154.12.245.181']
        caddy_plugins: ["github.com/greenpau/caddy-security"]
    - role: authentik
      vars:
        authentik_cleanup: true

  