---
- name: To configure my server(s)
  hosts: moontron
  gather_facts: true

  tasks:
    - name: Test task
      ansible.builtin.debug:
        msg: "hello?"
    - name: Delete caddy directory
      ansible.builtin.file:
        path: "/root/caddy/"
        state: absent
    - name: Create rathole config
      ansible.builtin.file:
        path: "/root/rathole/config"
        state: directory
        mode: '0775'
    - name: deploy template
      ansible.builtin.template:
        src: "templates/ext-rathole-server.toml.j2"
        dest: "/root/rathole/config/config.toml"
        mode: '0644'
    - name: Deploy rathole podman container
      containers.podman.podman_container:
        name: rathole
        image: docker.io/moonpiedumplings/rathole
        network: host
        volumes:
          - "/root/rathole:/config/"
        command: "rathole --server /config/config.toml"

