---
- name: To configure my server(s)
  hosts: moontron
  gather_facts: true

  roles:
    - name: rathole
      vars:
        rathole_role: "server"
        rathole_user: root
        rathole_server_ip: "154.12.245.181"

  tasks:
    # - name: Create rathole config
    #   ansible.builtin.file:
    #     path: "/root/rathole/config"
    #     state: directory
    #     mode: '0775'
    # - name: deploy template
    #   ansible.builtin.template:
    #     src: "templates/ext-rathole-server.toml.j2"
    #     dest: "/root/rathole/config.toml"
    #     mode: '0644'
    # - name: Deploy rathole podman container
    #   containers.podman.podman_container:
    #     name: rathole
    #     image: docker.io/moonpiedumplings/rathole
    #     network: host
    #     volumes:
    #       - "/root/rathole:/config/"
    #     command: "rathole --server /config/config.toml"

