- name: Do work as podmaner user
  become: true
  become_user: "{{ caddy_user }}"
  block:
    - name: Get $HOME environment variable
      ansible.builtin.command: "echo $HOME"
      register: homepath
      changed_when: false
    - name: Create caddy directory
      ansible.builtin.file:
        path: "{{ homepath.stdout }}/caddy/{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "config"
        - "data"
        - "caddy_config"
    - name: Create caddy configs
      ansible.builtin.template:
        src: "templates/Caddyfile.j2"
        dest: "{{ homepath.stdout }}/caddy/config/Caddyfile"
        mode: '0644'
    - name: Run podman caddy container
      containers.podman.podman_container:
        name: caddy
        image: docker.io/caddy
        state: started # or absent
        network: host
        volumes:
          - "{{ homepath.stdout }}/caddy/config/Caddyfile:/etc/caddy/Caddyfile"
          - "{{ homepath.stdout }}/caddy/data:/data"
          - "{{ homepath.stdout }}/caddy/caddy_config:/config"
        cap_add:
          - NET_ADMIN
        restart_policy: "on-failure"
        force_restart: true
