- name: Do work as podmaner user
  become: true
  become_user: "{{ caddy_user }}"
  block:
    - name: Get $HOME environment variable
      ansible.builtin.command: "echo $HOME"
      register: homepath
      changed_when: false
    - name: Caddy cleanup
      when: caddy_cleanup
      ansible.builtin.file:
        path: "{{ homepath.stdout }}/caddy"
        state: absent
    - name: Create caddy directory
      ansible.builtin.file:
        path: "{{ homepath.stdout }}/caddy/{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "config"
        - "data"
        - "caddy_config"
    - name: Create caddy configs
      ansible.builtin.template:
        src: "templates/Caddyfile.j2"
        dest: "{{ homepath.stdout }}/caddy/config/Caddyfile"
        mode: '0644'
    - name: Template caddy dockerfile
      ansible.builtin.template:
        src: templates/Dockerfile.j2
        dest: "{{ homepath.stdout }}/caddy/Dockerfile"
    - name: Build caddy image
      containers.podman.podman_image:
        name: caddy
        path: "{{ homepath.stdout }}/caddy/"
        tag: latest
    - name: Delete dockerfile when done
      ansible.builtin.file:
        path: "{{ homepath.stdout }}/caddy/Dockerfile"
        state: absent
    - name: Delete caddy container
      containers.podman.podman_container:
        name: caddy
        state: absent
    - name: Run caddy container
      containers.podman.podman_container:
        name: caddy
        image: localhost/caddy
        #image: docker.io/library/caddy:{{ caddy_version }}
        state: started # or absent  
        recreate: true
        network: host
        volumes:
          - "{{ homepath.stdout }}/caddy/config/Caddyfile:/etc/caddy/Caddyfile"
          - "{{ homepath.stdout }}/caddy/data:/data"
          - "{{ homepath.stdout }}/caddy/caddy_config:/config"
        cap_add:
          - NET_ADMIN
        restart_policy: "always"
        force_restart: true
