---
- name: Do forgejo things
  become: true
  become_user: "{{ forgejo_user }}"
  block:
    # - name: Cleanup
    #   when: forgejo_cleanup
    #   ansible.builtin.file:
    - name: Ensure forgejo data folders exist
      ansible.builtin.file:
        path: forgejo/{{ item }}
        mode: '0755'
      loop: ['data']
    - name: Podman pod
      containers.podman.podman_pod:
        name: forgejo_pod
        recreate: true
        userns: keep-id:uid=1000,gid=1000
        state: started
        # ports:
        #   - "9000:9000"
        #   - "9443:9443"
        #   - "3389:3389"
        #   - "6636:3389"
    - name: Build postgres image
      containers.podman.podman_image:
        name: moonpiedumplings/forgejo_postgres
        path: "{{ homepath.stdout }}/forgejo/postgres/"
        tag: 12
    - name: Delete dockerfile when done
      ansible.builtin.file:
        path: "{{ homepath.stdout }}/forgejo/postgres/Dockerfile"
        state: absent
    - name: Forgejo postgres database
      containers.podman.podman_container:
        recreate: true
        state: started
        name: forgejo_postgres
        pod: forgejo_pod
        user: 1000:1000
        image: "moonpiedumplings/forgejo_postgres:12"
        # image: "docker.io/library/postgres:12-alpine"
        # healthcheck: 
        volumes:
          - "{{ homepath.stdout }}/forgejo/postgres:/var/lib/postgresql/data"
        env:
          forgejo_SECRET_KEY: "{{ forgejo_secret_key }}"
          POSTGRES_PASSWORD: "{{ forgejo_postgres_password }}"
          POSTGRES_USER: "{{ forgejo_postgres_user }}"
          POSTGRES_DB: "{{ forgejo_postgres_db }}"
    - name: 

        
  