FROM caddy:{{ caddy_version }}-builder AS builder

RUN xcaddy build \
    {% for module in caddy_modules %}
    --with {{ module }} \

FROM caddy:{{ caddy_version }}

COPY --from=builder /usr/bin/caddy /usr/bin/caddy